### ISSUE TITLE
react-mentions with Rails?

### ISSUE THREAD

**Issue by astamm78** [effektif/react-mentions#100]
Not an issue, but I'm stuck on how best to pull this library into my Rails app.

I'm currently using React in my app via the 'react-rails' gem.

    source 'https://rubygems.org'

    gem 'rails', '4.2.4'    

    gem 'browserify-rails'
    ....
    gem 'react-rails', '~> 1.6.0'
    ...

I tried adding the 'browserify-rails' gem and installing 'react-mentions' . I'm seeing a 'react-mentions' folder in the node_modules directory in my Rails app, but I'm unclear on how to get access to the 'react-mentions' library in my application.js file.

```javascript
//= require jquery
//= require jquery_ujs
//= require bootstrap-sprockets
//= require react
//= require react_ujs
//= require components

//= require_tree .
```

Using the `import { MentionsInput, Mention } from 'react-mentions'` line doesn't seem to play nice with Rails.

**Comment by jfschwarz** [comment]
`import { MentionsInput, Mention } from 'react-mentions'` is ES6 syntax. With browserify you should use:

```
var reactMentions = require('react-mentions');
var MentionsInput = reactMentions.MentionsInput;
var Mention = reactMentions.Mention;
```

**Comment by astamm78** [comment]
@jfschwarz Thank you very much, I'll plug this in and see what happens!
