### ISSUE TITLE
Cursor will jump to the end when use value from props

### ISSUE THREAD

**Issue by bearpku** [effektif/react-mentions#104]
I am using redux as the react store instead of the state inside of the component.
I found an interesting bug that every time I type something in the textarea, the cursor will jump to the end of the sentence.

here is my code:

```
<MentionsInput
  value={this.props.value}
  onChange={this.handleChange}
  className="form__mention"
  markup="%{__display__}"
>
  <Mention
    trigger="@"
    data={suggestions}
    className="form__mention-item"
  />
</MentionsInput>
```

if I use a state inside of the component, and change `this.props.value` to `this.state.value`, the error fixed. But if I use the value from the props, the cursor will jump.

**Comment by jfschwarz** [comment]
This is definitely a bug in your app then. It might be helpful to use the redux-logger middleware to check whether your state updates go through correctly.

**Comment by bearpku** [comment]
@jfschwarz  No it's not a bug in my app.
If I directly use textarea instead of MentionInputs, it works.

```
<textarea
  rows={this.props.rows}
  name={this.props.name}
  value={this.props.value}
  onChange={(e) => handleInputChange(this.props.name, e.target.value)}
/>
```

**Comment by nikoanzai** [comment]
I have the same issue. Any workaround @linghu-chong?

**Comment by jfschwarz** [comment]
Please track your render function calls. You are probably re-rendering mentions input with an outdated state, meaning that after a change you render with the old value once before rendering with the new value.

**Comment by Vimallakzz** [comment]
I have the same issue. I used semi - controlled components, which means you can store the changes in local state and as well as redux state . For Edit we can get from redux state and set in local state. Refer this https://gist.github.com/rchanou/0a5c4173803a0d654f4c986d696a5c7f
