### ISSUE TITLE
Possible to trigger in the middle of words?

### ISSUE THREAD

**Issue by TheLudd** [effektif/react-mentions#107]
Hello
I currently use react-mentions with the "@" trigger. However, the trigger only works if it is proceeded by a white space. In my app, I use react-mentions in order for users to enter formulas with a set of pre defined variables to use. An example could look like this: `@price * (1 + @taxRate)`

I would like to be able to allow the user to enter that formula without the white spaces so that if they write: `@price*(1+@` the select box would now show. I have not found the right regexp to use for this case. I had assumed something like `\s*@` but if I use that I get this error: 
`react-mentions:13835 Uncaught TypeError: Cannot read property 'length' of undefined` (line 13835)

Is it possible to achieve what I want?

**Comment by jfschwarz** [comment]
Yes, it's possible.

It's crucial to use a regexp with [capturing groups](http://stackoverflow.com/a/432503), because this is how react-mentions knows which part of the trigger match it should replace with the mention markup (first capturing group) and which part it should extract as the search query (second capturing group).

For an example of a custom regex matching email addresses, have a look at: https://github.com/effektif/react-mentions/blob/master/gh-pages/views/examples/MultipleTriggerView.js#L11

**Comment by TheLudd** [comment]
Thanks for the guidance.

I ended up trying this regexp `/(@(\w*))$/` and it almost works but there is a strange side effect:
 * If I just enter "@" all options show up, this is good and expected
 * If I enter "@" followed by exactly one letter, no options show
 * If I enter "@" followed by two or more letters, all matching options show up.

Is there any reason why nothing shows up for the one letter case?

**Comment by jfschwarz** [comment]
Hmm, this is strange. What are you passing down as the `data` prop, an array or a filtering function?

**Comment by TheLudd** [comment]
An array of objects with id and display properties

**Comment by jfschwarz** [comment]
Sorry, I cannot reproduce this. I created an example view like this:

```
<MentionsInput
          value={this.state.value}
          onChange={value => this.setState({ value })}>

          <Mention
            trigger={/(@(\w*))$/}
            data={[{id: "foo", display: "foo"}, {id: "bar", display: "bar"}]} />
</MentionsInput>
```

It works fine, for none, one, and more than one letters after the '@'.

**Comment by TheLudd** [comment]
The error is still there for me, even if I use the same data as you.
Could it perhaps be that I use a custom display transform looking like this 
`displayTransform={(id, display) => `@${display}`}`

When my users have entered a variable I actually want the @ to still be there.

**Comment by linsmalldragon** [comment]
@jfschwarz same issue

**Comment by linsmalldragon** [comment]
@TheLudd use /(@(\W*))$/  will be ok.

**Comment by DiagoSmith** [comment]
So I just came across a very similar problem today, and also found that the aforementioned regex failed after typing more than the initial '@'. 

I got it working by changing the W to be a lowercase w. Hope this helps anyone else who spent a long time scratching their heads.
