### ISSUE TITLE
onBlur firing

### ISSUE THREAD

**Issue by winkler1** [effektif/react-mentions#108]
Thanks for this component - just what we needed. Love having multiple triggers also!

Problem: `onBlur` is firing when dropping down the suggestions. This is triggering auto-save code in onBlur and causing issues for me. 

Seems like `MentionsInput.handleBlur` should only call `this.props.onBlur` if the overlay is not showing, to only get blur events when the user tabs out?

Thanks

**Comment by winkler1** [comment]
user-space workaround: guard onBlur with a call to 
```
function isSuggestionsDropdownShowing(mentionsRef) {
  const suggestions = mentionsRef.state.suggestions;
  const isShowing = (suggestions && Object.keys(suggestions) > 0);
  return isShowing;
}
```

**Comment by jfschwarz** [comment]
Not sure, if it would be good to not fire `onBlur` when dropping down the suggestions. After all, the textarea does loose focus... 

We might pass a `isSuggestionsDropdownShowing` flag as a second parameter to the `onBlur` callback.

**Comment by winkler1** [comment]
Sure, a `isSuggestionsDropdownShowing` flag would be fine

**Comment by udonmai** [comment]
Liked this! Thanks!
