### ISSUE TITLE
Unknown prop `_radiumDidResolveStyles` on <div> tag.

### ISSUE THREAD

**Issue by jmblog** [effektif/react-mentions#110]
I'm getting a warning with React 15.2.0.

```
Unknown prop `_radiumDidResolveStyles` on <div> tag.
```

Ref: https://gist.github.com/jimfb/d99e0678e9da715ccf6454961ef04d1b

**Comment by tinyx** [comment]
Same here

**Comment by jfschwarz** [comment]
We'll have to wait for a fix for https://github.com/FormidableLabs/radium/issues/759

**Comment by tinyx** [comment]
Thanks for replying @jfschwarz , I'll try that out!

**Comment by jmblog** [comment]
@jfschwarz I've updated to 0.5 and confirmed the warning is gone. Thanks!
