### ISSUE TITLE
Optional Radium breaks in Browserify

### ISSUE THREAD

**Issue by jfschwarz** [effektif/react-mentions#113]
https://github.com/effektif/react-mentions/commit/2f9721ff867739ee466e84edc5c63728c8b8bdea#commitcomment-18373575

**Comment by jfschwarz** [comment]
For a workaround see: https://github.com/effektif/react-mentions/commit/2f9721ff867739ee466e84edc5c63728c8b8bdea#commitcomment-18618695

**Comment by jfschwarz** [comment]
A short summary:

- webpack will show a warning during build. We currently don't see a way to get rid of this warning. However, it seems acceptable that a warning is shown if an optional dependency is not installed.
- browserify requires some extra configuration if you want to use react-mentions without radium. You can use the `exclude` option or the [browserify-optional](https://www.npmjs.com/package/browserify-optional) transform

**Comment by burakcan** [comment]
A workaround for webpack users. Add this alias to your config and it will not show a warning:

``` javascript
resolve: {
    alias: {
      radium: 'lodash/identity',
    },
  },
```
