### ISSUE TITLE
add support for onKey* callbacks

### ISSUE THREAD

**Issue by alexkrolick** [effektif/react-mentions#117]
E.g. I might want to add a handler for cmd+enter to submit the input

**Comment by jfschwarz** [comment]
All onKey* are already supported. What is not working for you?

**Comment by alexkrolick** [comment]
Cool, it works. Didn't see it in the docs: https://github.com/effektif/react-mentions#configuration

**Comment by jfschwarz** [comment]
We pass all props that we don't consume in the `MentionsInput` through to the input. This means you can just use all the standard HTML attributes.
