### ISSUE TITLE
Can't write in the input field

### ISSUE THREAD

**Issue by dabdada** [effektif/react-mentions#119]
Hi I am looking for a mentioning component for one of my projects and came accross this react-mentions component.

But when I use it within my component it gets rendered without any problems (no errors in the console or anywhere) but I cannot write any text in the mention textarea nor in the singleline inputy type=text field.

Here is my code as far as I got:

    <MentionsInput
      className="FormControl"
      placeholder={gettext('Your comment ...')}
      style={mentionIputStyle}
      singleLine={true}
    >
      <Mention
        type="user"
        trigger="@"
        data={mentionableUsers}
      />
    </MentionsInput>

Where mentionableUsers is an array with objects containing display and id.

Is there anything I have to take care further?

**Comment by jfschwarz** [comment]
The `MentionsInput` can currently only be used as a controlled component, meaning you will have to keep the `value` in the state and update it in the `onChange` handler. (For some background on React controlled components, see: https://facebook.github.io/react/docs/forms.html#controlled-components.)

**Comment by dabdada** [comment]
ahhh thank you very much.
