### ISSUE TITLE
MentionsInput breaks on LinkedValueUtils dependency with React 15.4.0

### ISSUE THREAD

**Issue by dschilperoord** [effektif/react-mentions#124]
`MentionsInput` requires `react/lib/LinkedValueUtils`, which no longer exist in React 15.4.0. Apparently these utils have been moved to `react-dom/lib/LinkedValueUtils`. Also see https://github.com/facebook/react/commit/0f004efce2dcd0189a663f5724853eab261782e6.

**Comment by jfschwarz** [comment]
Thanks for reporting. Fixed in v0.6.0
