### ISSUE TITLE
ID only markup with display input

### ISSUE THREAD

**Issue by amitava82** [effektif/react-mentions#126]
Essentially, I'm looking for output value to be something like `Hi [123]` where `123` is the ID and input value to be `Hi Sam` where Sam is the display value. Setting markup to `[__id__]` renders the id in the input not the display. Is it possible ?

**Comment by jfschwarz** [comment]
Yes, it's possible using the `displayTransform` prop, which takes a function with the mention's `id` as first argument and is expected to return the string value for display.

**Comment by amitava82** [comment]
Yes, I tried it, however, it seems to be not working as expected
```
  renderDisplay(id, display, type){
    console.log(display); //This returns id value
    return display;
  }
```

**Comment by jfschwarz** [comment]
Well, obviously you will have to provide the mapping of the ID to the username. S.th. along the lines of:

```
<MentionsInput
  displayTransform={(id) => getUsernameById(id)}
  ...
/>
```

**Comment by amitava82** [comment]
Ah, I see. In this case I'll have to keep reference to the users list since it is loaded through  ajax. Is there anyway to get hold of the selected entity in `displayTransform` function? I was hoping `display` should already have the value.

**Comment by jfschwarz** [comment]
No, currently you will have to take care of this on your own.

(Actually, I never thought about doing that, but it could be a sensible extension of the default implementation of `displayTransform` to try to find the corresponding entry by ID within the synchronously provided Mention's `data`, if the markup does not directly contain the display value... 🤔)
