### ISSUE TITLE
react-mentions throwing React.createElement warning

### ISSUE THREAD

**Issue by wsmd** [effektif/react-mentions#131]
The components seems to work fine including autocompletion suggestions, mentions, etc... However, it keeps throwing the following warnings (see screenshots) as I interact with the element `change`, `blur`, `focus`.

![image](https://cloud.githubusercontent.com/assets/2100222/20692325/203ec2a0-b5a5-11e6-8023-4fdc2e05376f.png)

```jsx

import { MentionsInput, Mention } from 'react-mentions';

<MentionsInput
  className="CommentForm-input"
  value={this.state.body}
  placeholder="Write a comment"
  onChange={this.handleChange}
>
  <Mention
    trigger="@"
    data={MENTIONS_DATA}
    renderSuggestion={this.renderUserSuggestion}
    appendSpaceOnAdd
  />
</MentionsInput>
```

`MENTIONS_DATA` is just an array of the form `[{ id, display }]`

![screen shot 2016-11-28 at 7 49 10 pm](https://cloud.githubusercontent.com/assets/2100222/20692131/eb456550-b5a3-11e6-9d92-dae720747f9c.png)

![screen shot 2016-11-28 at 7 50 18 pm](https://cloud.githubusercontent.com/assets/2100222/20692130/e8f30596-b5a3-11e6-9b1e-b4c5c151a2f2.png)

Is there anything I'm missing?

I'm using `"react": "15.1.0"`

**Comment by jfschwarz** [comment]
This warning has been removed in React 15.3. Upgrading React to get rid of it.

For some more background, see: https://github.com/babel/babel/issues/4416, https://github.com/facebook/react/pull/7724

**Comment by wsmd** [comment]
@jfschwarz thanks for the quick response. I'll give that a try!
