### ISSUE TITLE
How to enable trigger only when typing two characters after @

### ISSUE THREAD

**Issue by warjohn123** [effektif/react-mentions#136]
I just would like to ask if how do you enable the mention trigger after typing two characters after @. Thanks :)

**Comment by jfschwarz** [comment]
You can set a custom regexp as the `Mention`'s `trigger`:

```
<Mention
  trigger={/(?:^|\s)(@([^@]{2,}))$/}
  ...
/>
```

The first (outer) capturing group must match the entire sequence for which mention suggestions should be displayed when found at the left of the cursor. The second (inner) capturing group is used to extract the actual search query, in this case stripping off the '@' char.
