### ISSUE TITLE
Textarea cannot be editable

### ISSUE THREAD

**Issue by warjohn123** [effektif/react-mentions#137]
I tried using the basic display of the MentionInput component. When it rendered, textarea is displayed well but when I type anything, it can't be edited. Any idea about this problem? Thank you.

**Comment by jfschwarz** [comment]
This sounds as if your app does not properly update the state on changes from the textarea (or state updates are not reaching the MentionsInput component). If you set a static value for the `value` prop, MentionsInput (just as any other React input component) we be read-only.

You might have to study a bit on React basics, especially the docs section on forms is quite relevant to your problem: https://facebook.github.io/react/docs/forms.html

**Comment by warjohn123** [comment]
But I did not set value for my textarea which is really confusing

**Comment by jfschwarz** [comment]
Hmm.... Could you paste your code or even create a jsfiddle that shows the problem?

**Comment by warjohn123** [comment]
<MentionsInput
              placeholder={Translator.trans('label.placeholder_comment', {}, 'comment')}
              name="newComment"
              ref="newCommentTextareaRef"
              onChange={this.handleNewCommentChange}
              markup="[__display__:__id__]">
            <Mention
                trigger={/(?:^|\s)(@([^@]{2,}))$/}
                data={this.getUsers()}
                appendSpaceOnAdd="true"
                style={{backgroundColor: '#249bd6'}}
                renderSuggestion={this.renderSuggestion}/>
          </MentionsInput>

That is the code that I'm writing right now. I tried putting console.log() in handleNewCommentChange but nothing is logged.

**Comment by jfschwarz** [comment]
Ah, I see. The problem is exactly that you do *not* set the value prop, as the MentionsInput can currently not be used in an uncontrolled fashion. See also: https://github.com/effektif/react-mentions/issues/119

**Comment by warjohn123** [comment]
I see. So, I already put value prop in the MentionsInput. Now here comes another error which says Required prop `value` was not specified in `Highlighter`. Check the render method of `MentionsInput`.

Any thoughts about this? Thank you very much.

**Comment by jfschwarz** [comment]
My guess would be, that your `value` prop is `undefined`. `MentionsInput` just always passes `this.props.value` through to the `Highlighter`. Please investigate a bit more, set a breakpoint in `MentionsInput`'s `renderHighlighter`, etc.

**Comment by QianWenW** [comment]
> Hmm.... Could you paste your code or even create a jsfiddle that shows the problem?

How do I invoke components in jsfiddle?
