### ISSUE TITLE
How to clear the textarea

### ISSUE THREAD

**Issue by warjohn123** [effektif/react-mentions#138]
Hi, I currently have this code : 

<MentionsInput
              placeholder={Translator.trans('label.placeholder_comment', {}, 'comment')}
              value={this.state.newComment}
              name="newComment"
              ref="newCommentTextareaRef"
              onChange={this.handleNewCommentChange}
              className="comment-mention-textarea"
              markup="[__display__:__id__]">
            <Mention
                trigger={/(?:^|\s)(@([^@]{2,}))$/}
                data={this.state.items}
                appendSpaceOnAdd="true"
                style={{backgroundColor: 'rgba(44,187,215,0.3)'}}
                renderSuggestion={this.renderSuggestion}/>
          </MentionsInput>

And I want to clear this textarea after I click a particular button. I tried using this code ReactDOM.findDOMNode(this.refs.newCommentTextareaRef).value = null; but it did not work. I also tried jQuery but didn't work too. For this case, how should we do it? Thank you very much.

**Comment by jfschwarz** [comment]
how about setting `this.state.newComment` to `null`?
