### ISSUE TITLE
How to feed data to Mention only when the user inputs in the textarea

### ISSUE THREAD

**Issue by warjohn123** [effektif/react-mentions#139]
I have this ajax get method to call an api that will return the users based on the string that's being passed or even all users in db. My question is, what's the best technique to do it if I only want that my ajax method will be called upon typing @ ? Thank you very much.

**Comment by frontendphil** [comment]
I'm not sure that I completely understood what you want to achieve, but you could, for instance, only send out requests if the `query` param of the callback function is `''` (empty string). 

However in your use case, I would recommend debouncing the request while the user is typing and then only retrieving a subset of your data.
