### ISSUE TITLE
Highlighting in text area is out of position, and moves moves left when typing more text.

### ISSUE THREAD

**Issue by Tran-Eric** [effektif/react-mentions#140]
Hi,

When mentioning a user, the highlight appears in the middle of the textarea, and when typing more text the textarea moves with each character to the left. Im thinking I should be adding more style to the highlighted class? Provided a picture.

<img width="472" alt="screen shot 2016-12-21 at 10 01 48 pm" src="https://cloud.githubusercontent.com/assets/22774900/21416659/8138d2fe-c7c9-11e6-8be6-f76e9667f6d3.png">

<img width="470" alt="screen shot 2016-12-21 at 10 05 22 pm" src="https://cloud.githubusercontent.com/assets/22774900/21416672/9cfd2a4e-c7c9-11e6-9ef7-d7777baac63e.png">

**Comment by frontendphil** [comment]
Hey @Tran-Eric could you share your setup? I see some extra styles. Also it would be interesting which browser you used.

**Comment by Tran-Eric** [comment]
i figured it out. I had css property text-align: center inherited from the parent.
