### ISSUE TITLE
Custom markup issue

### ISSUE THREAD

**Issue by alexandreneves** [effektif/react-mentions#144]
I'm integrating react-mentions on a platform which as already a mentions system working with the following markup server side `@username`. When trying to set `markup="@__display__"` `or ="@__id__"` to get everything working directly I'm having some issues - the "@" gets removed from the input as soon as typed.

**Comment by alexandreneves** [comment]
Oops -> #19

**Comment by mxstbr** [comment]
Did you ever resolve this @alexandreneves?

**Comment by alexandreneves** [comment]
> Did you ever resolve this @alexandreneves?

Hey @mxstbr, yes, but I have no idea how. It's been too long and I'm no longer working on that project.
