### ISSUE TITLE
How to get the markup Value for edit ?

### ISSUE THREAD

**Issue by killerdejavu** [effektif/react-mentions#146]
When I try to create content from scratch I store two values in state (plain_text and markup_text) and pass the markup text everywhere and this works perfectly. So when I want to send data to the server I send plain text (I already have my own parser in backend). 

But now when I want to edit the content I have to set the initial state with the plain text as I have not persisted data to the backend. Due to which the mentions, highlight doesn't work. Is there any other work around than to persisting the data to backend?

**Comment by jfschwarz** [comment]
I don't quite get how your backend parses the plain text. You should persist the markup not the plain text. How is react-mentions supposed to reconstruct mentions from just the plain text?

**Comment by killerdejavu** [comment]
We use only id when we store in backend. eg `<@member:5>` But if I define my markup as `<@member:__id__>` then for the function `displayTransform` I will not be able to get the display variable. All the three params come with the value of id.  So now I cannot use `display`  in my transformation.

**Comment by jfschwarz** [comment]
`displayTransform` is called with the parameters react-mentions extracts from the markup. Since, your markup only includes a placeholder for `id`, react-mentions will default the values for all `displayTransform` parameters to the extracted id value.

I still don't have a clear picture about your API data model. Could you post an example of the JSON you send to the backend?

**Comment by killerdejavu** [comment]
Let me try to simplify. We have a member table which has id and name (id is unique).  
eg. 
```id : 1 -> name: Manan```
```id:2 -> name: Abc```

And then we have some content table where we want to stores some content which has mentioned members. 
eg `Hey my name is <@member:2>` 
Here 2 is the id.

While displaying in the text area I want to display the name. `Hey my name is @Abc`

My issue is I don't want to store the id as well as the name in the db as this will be just duplication and I already have previous data with that markup.


Btw thanks for helping of this! Much appreciated.

**Comment by jfschwarz** [comment]
Alright, you already found the right mechanism to achieve what you want: `displayTransform`

Let's say you hold your members table in an plain object that looks like this:

```
const members = {
  "1": { "name": "Manan", ... }
  "2": { "name": "Abc", ... }
}
```

Then your display transform function will look s.th. like this:

```
function displayTransform(id) {
  return '@' + members[id]
}
```

Hope this helps.

**Comment by killerdejavu** [comment]
Oh! Basically I need a map from id to name(or object) instead of just a list of objects. Yup that will work! Thanks man 👍
