### ISSUE TITLE
Unable to enter text in the MentionsInput

### ISSUE THREAD

**Issue by christophedebatz** [effektif/react-mentions#147]
Hi everyone,

I'm currently using this great component in my react project but there is a problem for me.

I've that code in my component:

```
<MentionsInput
   value={this.state.text}
   onChange={this.onTextChange}
   placeholder={"Mention people using '@'"}
>
   <Mention trigger="@" data={editorStore.searchPages} appendSpaceOnAdd />
</MentionsInput>
```

On the textChange function, there is a simple console.log(event.target.value) that prints me each character I'm currently entering.

The textarea:

![selection_119](https://cloud.githubusercontent.com/assets/3020403/22704617/9e837e58-ed68-11e6-9c76-3bff557e11a0.jpg)

NB: I've also a warning when I use npm start:

```
WARNING in ./~/react-mentions/lib/OptionalRadium.js
Module not found: Error: Cannot resolve module 'radium' in /home/christophe/ws/nuke-admin-> front/node_modules/react-mentions/lib
@ ./~/react-mentions/lib/OptionalRadium.js 15:11-28
```

The problem is that I can't entered any text in the textarea, nothing is displayed as if something prevented the character input... I tried to remove the whole parameters and just keep the <MentionsInput /> tag but it remains the same. Any idea guys please?

Thanks per advance.

**Comment by daftgopher** [comment]
@christophedebatz Just tried this plugin out and got the same error. Were you able to resolve this?

**Comment by hew** [comment]
@christophedebatz I am facing this same issue. Did you ever resolve it?

**Comment by daftgopher** [comment]
I had the same problem earlier but solved it - you need to pass in the value from the state of a parent component. Mentions is a controlled component that depends on the state to render its internal value. Something like this `<MentionsInput value={this.state.text}>`

**Comment by hew** [comment]
Hmm. @daftgopher Mind taking a quick look at https://github.com/hew/react-mentions-example/blob/master/src/App.js ? 

I see that [the examples](https://github.com/effektif/react-mentions/blob/master/gh-pages/views/examples/SingleLineView.js) are using `createClass()` with a mixin.... hence my question in https://github.com/effektif/react-mentions/issues/152

**Comment by hew** [comment]
Yeah I couldn't get it to work without the mixin (which is basically just calling `setState()`). I'll just roll with the es5 component syntax for now.

**Comment by daftgopher** [comment]
Ah, I see the problem. Sorry I forgot to mention, you also need to pass in `onChange` to `<MentionsInput>` and a handler as well. You can use it with ES6 using something like this:

```
class App extends Component {
  constructor(){
    super()
    this.state = {
      aValue: 'beep beep',
      users: users
    }
  }
  
  handleChange(event){
    this.setState({
      aValue: event.target.value,
    });
  }

  render() {
    return (
      <div className="App">
        <MentionsInput
          value={this.state.aValue}
          placeholder={"Mention people using '@'"}
          onChange={this.handleChange.bind(this)}>
          <Mention data={ this.state.users } />
        </MentionsInput>
      </div>
    );
  }
}

export default App;

```

**Comment by hew** [comment]
@daftgopher Ahh. You know what? I had that but forgot the `(event)` param for the `handleChange` call. Thanks for the response!
