### ISSUE TITLE
Remove mixin to simplify examples

### ISSUE THREAD

**Issue by hew** [effektif/react-mentions#152]
Hey quick question: does `react-mentions` work without the `react-mentions` mixin? I see that all the examples make use of it, but the mixin is not mentioned in the main README.

**Comment by arahansen** [comment]
If you look at what the mixin is doing, its just abstracting calls to `setState`

https://github.com/effektif/react-mentions/blob/master/gh-pages/views/mixins/MentionsMixin.js

Probably overkill, and not necessary for the component to work, as long as you provide your own `onChange` function

**Comment by jfschwarz** [comment]
The mixin is only part of the examples. I agree that this kind of abstraction in examples is rather confusing than helpful. We should simplify the examples.

Where you keep your state is up to you. Just provide `value` and `onChange` props to `MentionsInput`.

**Comment by jfschwarz** [comment]
done with #154
