### ISSUE TITLE
why the getPlainText function is not accessible anymore?

### ISSUE THREAD

**Issue by Shnolik** [effektif/react-mentions#156]
I've used react mentions 0.6.2, and using a ref to the MentionsInput, I called the getPlainText method.
Today, I've upgraded to 1.0.0 and I am getting a "not a function" error when calling the getPlainText.

Thanks for your advise.

**Comment by jfschwarz** [comment]
Could you try changing the call to `yourRef.getWrappedInstance().getPlainText()`?

In general, I would suggest to change your code to handle the `onChange` and store the third argument, which is the plain text value, in a component state, instance field, or similar. The imperative style of accessing instance methods directly is not React-idiomatic and those methods are also not part of react-mentions public API.
