### ISSUE TITLE
Issue with JSX in /lib

### ISSUE THREAD

**Issue by mtetlow** [effektif/react-mentions#16]
I have added: "react-mentions": "*" to my "dependencies" in my package.json. Then I run `npm install`, which correctly pulls down the files. When I try to reference via `var ReactMentions = require('react-mentions');` I receive a compilation error: `/node_modules/react-mentions/lib/MentionsInput.js: Unexpected token (99:6)` when browserify builds a bundle. It appears this is because there is JSX in MentionsInput.js . An attempt to include the dist file directly results in another error because I do not have a global reference to React.

Any chance you guys are interested in getting compiled jsx in the /lib directory? It appears react-bootstrap developers in /src and populates /lib and /dist with compiled files.

**Comment by jfschwarz** [comment]
Makes sense, thanks for the feedback. JSX sources are now in /src and the build writes the transpiled files to /lib.
