### ISSUE TITLE
Asynchronous data prop in Mention Component

### ISSUE THREAD

**Issue by shravya95** [effektif/react-mentions#163]
Hey, I need to fetch results on a query asynchronously, and i also have a doubt whether it is necessary for the data array to be of this form **{ id & display}** because i need a custom dropdown _with an image and name_ .The previous answer [did not explain the issue clearly.
](https://github.com/effektif/react-mentions/issues/39)

**Comment by frontendphil** [comment]
Hey @shravya95 the `{ id, display }` format is needed, as we use that internally. However this should not stop you from building our your use case. 

1. You can pass a function to `data` that requests you data asynchronously and uses the `callback` parameter to tell the mention component when data is ready. 
2. Pass a custom renderer to `renderSuggestion` to render suggestions in the way you want to. Your application simply needs a way to figure out how to map for instance `id` to an image + text.

**Comment by shravya95** [comment]
thanks for the quick reply
