### ISSUE TITLE
Selection index not updated while typing

### ISSUE THREAD

**Issue by maksis** [effektif/react-mentions#167]
Reproducing with your examples:

1. Type an empty mention (@) and highlight Mike Ehrmantraut by using arrow keys
2. Continue typing the highlighted name until the other options disappear. The selected option won't stay highlighted and you'll get a Javascript error when pressing enter.

**Comment by jfschwarz** [comment]
wow, I'm really wondering how this error could stay unnoticed for so long? thank you for reporting, I will look into this now.
