### ISSUE TITLE
Support for react@0.13.x

### ISSUE THREAD

**Issue by ahlee2326** [effektif/react-mentions#17]
npm WARN peerDependencies The peer dependency react@0.12.x included from react-mentions will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm ERR! Linux 3.16.0-34-generic
npm ERR! argv "/home/leesiongchan/.nvm/versions/io.js/v1.6.4/bin/iojs" "/home/leesiongchan/.nvm/versions/io.js/v1.6.4/bin/npm" "install" "--save" "react-mentions"
npm ERR! node v1.6.4
npm ERR! npm  v2.7.6
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package react does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer react-router@0.13.2 wants react@0.13.x
npm ERR! peerinvalid Peer react-mentions@0.1.2 wants react@0.12.x

**Comment by frontendphil** [comment]
As far as I am concerned I think we can safely release 0.2.0 with a peer dependency to react@0.13.x we should release  new version anyways because @jfschwarz has improved the support for IE.

**Comment by jfschwarz** [comment]
I fixed the react version dependency in the package.json. Please check if it works for you now, @ahlee2326
