### ISSUE TITLE
Suggestions list position thrown off when overriding MentionsInput style

### ISSUE THREAD

**Issue by jgrisafe** [effektif/react-mentions#174]
![screen shot 2017-08-01 at 3 00 26 pm](https://user-images.githubusercontent.com/7333411/28849088-538faaa2-76ca-11e7-96c9-cb1f0c46083c.png)
looks like the absolute positioning is thrown off when I add my own style object to the MentionsInput element. This example is merely overriding the styles with the exact defaultStyle object from the example with `style={defaultStyle}`

**Comment by frontendphil** [comment]
Hey @jgrisafe did you figure out what caused the problem?

**Comment by jgrisafe** [comment]
@frontendphil yeah it turns out I had the mention markup incorrect, when I switched it to `markup="@[__display__]"` it worked fine. I think I had `markup="@__display__"` before.
