### ISSUE TITLE
How to show the Suggestions Overlay while typing in the query and updating `data` prop?

### ISSUE THREAD

**Issue by seiji619** [effektif/react-mentions#175]
Thanks for the awesome library. I've been enjoying using it so far but I have one issue.

I'm trying to fetch the facebook page names while I type in the query, so the `data` prop of the `Mention` component changes on the fly. However, I don't see the updated suggestions as soon as the `data` prop is updated. I can only see it if I type in one more character (or remove it) or manually click on another component and click back on the `MentionsInput` to gain focus.

Is there any way for this? I tried keeping the component with `ref` callback and calling `focus()` but it does not exist because what I get is the React component's ref, not the ref of the `input` or the `textarea`.

**Comment by frontendphil** [comment]
Hey @seiji619 do you hand in a static list of values for `data`? Does this also happen, if you use the callback syntax?

**Comment by seiji619** [comment]
@frontendphil As I said, I send in a dynamic list of values because I fetch Facebook Page names while typing in the query. Yeah, I tried using the callback syntax but it was the same.

**Comment by frontendphil** [comment]
Hmm... that sounds very weird. We're using mentions in both sync and async scenarios and never encountered that. Could you by any chance provide us with a live code exampe?

**Comment by seiji619** [comment]
Hey @frontendphil sorry, I fixed it by using the callback. But I still want the ability to update the `data` prop and show the overlay immediately. I had to move the API call from redux structure to the component to use the callback syntax.

**Comment by frontendphil** [comment]
Closing this. My reasoning is, that if data can change asynchronously then the callback method would be the better way to implement that since it assumes async and changing data. The static `data` prop is, as the name suggests, for static data and therefore we don't assume changes.
