### ISSUE TITLE
Not working with dot (.)

### ISSUE THREAD

**Issue by tnhu** [effektif/react-mentions#179]
react-mentions currently does not work well if data has dot. For example:

```javascript
const data = [
  { id: "USER.NAME", display: "USER.NAME" },
  { id: "USER.EMAIL", display: "USER.EMAIL" }
]
```

When I type `USER`, suggestion still works. As soon as I type `USER.`, suggestion stops working.

Demo: https://codesandbox.io/s/v21mBpOR8

**Comment by Crayonn** [comment]
trigger={/(\@([A-Za-z0-9_.]*))$/}  
\w = [A-Za-z0-9_]

**Comment by tnhu** [comment]
Thanks @Crayonn!

**Comment by VeromcaWang** [comment]
Hello @tnhu, I'm new to react but I met a similar issue recently. Would like to see how did you solved this issue by using custom regex? The above mentioned links are no longer existing, therefore I would like to know if you used "regex" attribute in <MentionsInput> tag?

**Comment by tnhu** [comment]
@VeromcaWang I could not make it work the way I liked so we ended up building an in-house component. Sorry, it's not open-sourced.
