### ISSUE TITLE
Async suggestion list 

### ISSUE THREAD

**Issue by saidymadi** [effektif/react-mentions#183]
Hello 
I am sorry to ask you the same question again . I noticed few people asked it already  
however , 
I am not able to async populate my data in the suggestion list 

I wonder if you can post an example using axios on how to load up a json containing 
{
   [   {id: "user1", display: "user name one"}.  {id: "user2", display: "user name two"}. ] 
}

and display it in the suggestion list . 

FYI
https://www.npmjs.com/package/axios

**Comment by saidymadi** [comment]
oh I think you can add this example to help users understand async mentions

assuming you have axios installed in your package  npm install axios --save

in Examples.js 
```
import axios from 'axios'; 

//add new async data source 
var asyncData = function (query, callback) {
  axios.get('./views/examples/server-response/response.json').then((response) => {
    var data = response.data;
    const results = [];
    for (let i = 0, l = data.length; i < l; ++i) {
      const display = data[i].display ||  data[i].id;
      if (display.toLowerCase().indexOf(query.toLowerCase()) >= 0) {
        results.push(data[i]);
      }
    }
    return callback(results);
  });

};


//replace any of the data= props  to use the new async source  
 <SingleLine data={asyncData} />
```

This assumes that you have a json file 
./views/examples/server-response/response.json 
`[
  {
    "id": "walter",
    "display": "Walter White"
  },
  {
    "id": "jesse",
    "display": "Jesse Pinkman"
  },
  {
    "id": "gus",
    "display": "Gustavo Gus Fring"
  },
  {
    "id": "saul",
    "display": "Saul Goodman"
  },
  {
    "id": "hank",
    "display": "Hank Schrader"
  },
  {
    "id": "skyler",
    "display": "Skyler White"
  },
  {
    "id": "mike",
    "display": "Mike Ehrmantraut"
  }
]`

**Comment by frontendphil** [comment]
Hey @saidymadi maybe you could rewrite your example to use the [fetch API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API). Then most users (except IE) could use the example straight away and we wouldn't need any further dependencies. 

We would be happy to accept such a PR :)

**Comment by saidymadi** [comment]
I've created a PR as you suggested but when I try to push I get the following ; 

remote: Permission to effektif/react-mentions.git denied to saidymadi.
fatal: unable to access 'https://github.com/effektif/react-mentions.git/': The requested URL returned error: 403

**Comment by frontendphil** [comment]
You've got to fork this project and then create a PR. I think what you tried was to push directly to this repository, for which you have no rights ;)

**Comment by brigand** [comment]
@saidymadi still working on this, or can I do it?

**Comment by saidymadi** [comment]
I am sorry got busy with other work , I tried the fetch api and it worked fine , I just don't have rights to open PR directly and my forked version has deviated  a lot from this so . I am sorry to bug you but you can do it instead

**Comment by brigand** [comment]
https://github.com/effektif/react-mentions/pull/186

**Comment by jfschwarz** [comment]
@brigand's example has been merged and is now running live at http://effektif.github.io/react-mentions/
