### ISSUE TITLE
Require an example of using css to style the mention inputs 

### ISSUE THREAD

**Issue by saidymadi** [effektif/react-mentions#188]
could you show me an example of how to use css style sheet to style the components in 

basically I have library-stylesheet.css which got some properties (special animation for the loading indicator) + other customizations 

and when I run the sample app cuz it is using webpack things work 
but If I use my forked package and transpile it so I can use it as an npm package in another project . 

your transpile command does not handle or deal with css thus I end up having missing references to my library-stylesheet.css 

could you help me out ?

**Comment by jfschwarz** [comment]
For really bundling styles with an npm package, inline styles or css-in-js are the only things that work.

If you want to publish your package with css without making assumptions about the build tooling of your package's consumer, the best you can do is making sure that you document for your users that they will have to somehow import your css file. You can also reference you entry css file in the `style` field in the `package.json` (see: https://stackoverflow.com/questions/32037150/style-field-in-package-json), but only some bundlers will actually understand this.

Hope this helps.

**Comment by saidymadi** [comment]
I used gulp to minify and package my css with the src output 
steps are 

Install gulp 
npm install --save-dev gulp-install

add any style sheets to your project 
src/stylesheets/*.css

in the root dir where the package.json resides add a new file **gulpfile.js**
`let gulp = require('gulp');
let cleanCSS = require('gulp-clean-css');

gulp.task('minify-css', () => {
  return gulp.src('src/stylesheets/*.css')
    .pipe(cleanCSS({debug: true}, function(details) {
      console.log(details.name + ': ' + details.stats.originalSize);
      console.log(details.name + ': ' + details.stats.minifiedSize);
    }))
  .pipe(gulp.dest('./lib/stylesheets'));
});`

in package.json add the gulp minify command
 "transpile": "npm run env NODE_ENV=production && babel src --out-dir lib && **gulp minify-css**",



now anyone using your library will have to import these style sheets 
`import 'myfork-react-mentions/lib/stylesheets/loadingIndicatorStyle.css';
import 'myfork-eact-mentions/lib/stylesheets/socialMarkupInputStyle.css';`
