### ISSUE TITLE
Fix for inserting char right after email causing terrible errors

### ISSUE THREAD

**Issue by saidymadi** [effektif/react-mentions#189]
When you write in an email 
saidymadi@gmail.com 
if you move the cursor back to the end of that email and add any other charachters 
the suggestion menu will pop up and give you a new option to add that email as a mark up 

however that causes the following bug 

Here is the solution (too lazy to fork and apply then open a PR) : 

Add a new check to the renderSuggestionOverlay in MentionsInput.js

   renderSuggestionsOverlay = () => {
    const {value , markup , displayTransform} = this.props;
    if(!utils.isNumber(this.state.selectionStart)) {
      // do not show suggestions when the input does not have the focus
      return null;
    }

    if(utils.isRightAfterAMention(value, markup, this.state.selectionStart, displayTransform)) {
      //ignore and dont show suggestion if the user is typing chars after an email mention 
      //for example if we start with an email mention of saidymadi@gmail.com
      //then the user goes with curtor to the end of the email and type more chars saidymadi@gmail.comSAdsadsaWDSAD| 
      //we will not display a suggestion menu
      return null;
    }
    return (
      <SuggestionsOverlay
        style={ this.props.style("suggestions") }
        position={ this.state.suggestionsPosition }
        focusIndex={ this.state.focusIndex }
        scrollFocusedIntoView={ this.state.scrollFocusedIntoView }
        ref="suggestions"
        suggestions={this.state.suggestions}
        onSelect={this.addMention}
        onMouseDown={this.handleSuggestionsMouseDown}
        onMouseEnter={ (focusIndex) => this.setState({
          focusIndex,
          scrollFocusedIntoView: false
        }) }
        isLoading={this.isLoading()} />
    );
  };

**Comment by saidymadi** [comment]
add a new  Function in the utils.js


  // Returns whether the given plain text index lies inside a mention
  isRightAfterAMention: function(value, markup, indexInPlainText, displayTransform) {
    if(value){
      //email regex match any email followed by any length of spaces
      const emailRegex = /(([^\s@]+@[^\s@]+\.[^\s@]+ *))$/;

      let isRightAfterAnEmailMention = false;
      let plainText = this.getPlainText(value, markup, displayTransform);
      
      //optimization as we are only interested in the segment leading up to our carret position
      //therefor no need to handle the enter content
      plainText = plainText.substr(0,indexInPlainText);
 
      //gather all email mentions in the current segment 
      let emailMentionsList =  plainText.match(emailRegex);

      //only if we find email mentions
      if(emailMentionsList){
        for(let x = 0 ; x < emailMentionsList.length ; x++){
           let email = emailMentionsList[0];
           //investigate from the beggining of the email till our carret  
           let emailMentionIndex = plainText.indexOf(email);
           let partialString = plainText.substr(emailMentionIndex,indexInPlainText);
           
           //if we find a space char between the email and the current carret position then we conclude that we are not right after an email mention
           let isThereWhiteSpace = partialString.split(" ").length > 1;
           if(!isThereWhiteSpace){
             //here we confirmed that there is an email and our carret position is right after it ( there is no space between the email and our carret )
             //example saidm@gmail.coms|  or blabla@blabla.com1234555555|
             //we have to make sure that this particular email mention actually exists because user might be in the middle of typing an email
            let mentionStart = this.findStartOfMentionInPlainText(value, markup, emailMentionIndex, displayTransform);
            let emailMentionExists = mentionStart !== undefined && mentionStart !== indexInPlainText;
            //here we concluded  that there is an existing email markup and the user is trying to type some chars right after it
            //we should not show the overlay suggestion , and we should ignore this and treat it as text 
            isRightAfterAnEmailMention = emailMentionExists;
            break;
           }
        } 
      }
      return isRightAfterAnEmailMention;
    }
    else{
      return false;
    }  
  },

**Comment by jfschwarz** [comment]
Wow, I'm wondering how this has never been noticed before! It's indeed a rather terrible bug. Thank you for reporting. I will take a look at your fix later today.
