### ISSUE TITLE
onChange should return the entire mentioned user object

### ISSUE THREAD

**Issue by saidymadi** [effektif/react-mentions#192]
I have a facebook like comment box in my app.

when users mention other users and submit im using the onChange handler to get the latest list of mentioned users to then perform other actions on them (send them  email...etc)

when the on change handler is triggered from this react mentions component .
it calls back the users' (consumer) passed in on change function it returns the list of mentions as 
 [ {   id: xxxx , display: yyyy}, .... ]

in my case i have other properties associated with my object and would like this component to return the entire passed inn user object
[ { ... passedInUser} , ....]

because i need all the other fields to perform further actions on these mentioned users in my application. 

for example: my users can have : email,  avatar ....etc

and when they submit the post i want to be able to get the list of all mentions and do something with it

**Comment by frontendphil** [comment]
I just gave this another thought and this can easily be fixed in user land with a super small wrapping component. We actually do quite the same and have a `<UserMentiosn />` component in our apps at Signavio.

**Comment by ganeshmani** [comment]
@frontendphil  Can you explain a bit more in detail?

**Comment by MadhukarRagaji** [comment]
It would be really helpful if the component itself could return the object
