### ISSUE TITLE
Broken build?

### ISSUE THREAD

**Issue by jondeandres** [effektif/react-mentions#20]
Hi,

sorry, I'm having problems today trying to use your libary:

```shell
➜  ~  npm install react-mentions
react-mentions@0.1.4 node_modules/react-mentions
➜  ~  node
> require('react-mentions')
Error: Cannot find module 'react-mentions'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at repl:1:2
    at REPLServer.self.eval (repl.js:110:21)
    at Interface.<anonymous> (repl.js:239:12)
    at Interface.emit (events.js:95:17)
    at Interface._onLine (readline.js:202:10)
    at Interface._line (readline.js:531:8)
```

Have you broken the build maybe? I couldn't use it in two different hosts.

**Comment by jfschwarz** [comment]
It works for me:

```
➜  ~  npm install react-mentions
react-mentions@0.1.4 node_modules/react-mentions
➜  ~  node
> require('react-mentions')
{ MentionsInput: ...
  Mention: ... }
```

Did you just upgrade to version 0.1.4? In that case, you could try if version 0.1.3 still works for you: `npm install react-mentions@0.1.3`

Anyways, I would assume some misconfiguration on your end.

**Comment by jondeandres** [comment]
Yes, that worked when I executed `npm cache clean` and then install. 

Did you try with `npm install git://github.com/effektif/react-mentions#custom-regex` and having the cache clean? That seems to be broken, also with master.

**Comment by jfschwarz** [comment]
Ah alright, you were already using the branch.... Thanks for the hint, I just fixed the module's main in the package.json.

**Comment by jondeandres** [comment]
Thanks @jfschwarz, now it works ;-).
