### ISSUE TITLE
add css class to parent divs of textarea

### ISSUE THREAD

**Issue by MohanadI** [effektif/react-mentions#200]
Hello , 

How I can add css classes to the parent divs of textarea for example the parent divs is not full width 
![screenshot-local pro economies com-2017-10-12-10-31-51-268](https://user-images.githubusercontent.com/26893608/31484383-cb2f6a38-af38-11e7-81c9-1a1c112e8fbd.png)

any suggestions ?

**Comment by jfschwarz** [comment]
Simply pass a `className` prop to the `MentionsInput` element.

**Comment by MohanadI** [comment]
Thank you I did not noticed that className change with __something
