### ISSUE TITLE
Moving between mentions with arrows not scrolling component 

### ISSUE THREAD

**Issue by omerts** [effektif/react-mentions#202]
Hello,

Thanks again for the great lib.
When I create a long list of suggestions, that overflow their container size, thus creating a scroller. Moving between the mentions using the arrows doesn't scroll the container, causing the selected activities being out of the view port. 
Wanted to create a fiddle, but couldn't find a cdn version of this lib. 
Omer

**Comment by jfschwarz** [comment]
Actually, the suggestions does scroll the selected item into view. You can see this behavior live in the "Advanced options" example at http://effektif.github.io/react-mentions/.

Make sure you set the `overflow: 'auto'` styling on the `"suggestions__list"` element (see: https://github.com/effektif/react-mentions/blob/master/gh-pages/views/examples/Advanced.js#L14).

**Comment by omerts** [comment]
Thanks for the quick answer, you solution worked. I had put it one level higher on the "__suggestions" element, which didn't work.
