### ISSUE TITLE
Give more control over MentionsInput

### ISSUE THREAD

**Issue by renanpvaz** [effektif/react-mentions#203]
I'm building a very specific component that depends on click and focus events, however, `MentionsInput` only supports blur and change events. I think it would be nice to have more control over the input by, at least, allowing these two other props (onClick and onFocus) to be passed in. 

Another option (probably not viable) would be receiving a render prop for the input.

**Comment by renanpvaz** [comment]
I decided to make a small patch for personal use just to realize, by looking at the source, that it actually does support other props :smile:. 

So anyway, I'm closing this, but I still think it'd be good to mention that the input works that way.

**Comment by frontendphil** [comment]
We had that discussion a couple of time already. We think, that it is not worth mentioning, that we don't change the default.
