### ISSUE TITLE
Mention's background shifts

### ISSUE THREAD

**Issue by AlexBryuzgin** [effektif/react-mentions#205]
Good day
I've dealt with the case of background shifting when using a multiline input. 

As you can see on the picture, when the record is written some characters (at least 15) to the right from the beginning, the background starts to slide horizontally.
In case, when I move the record with `Enter` button, the background begins to slide vertically. 

All styles used for this are from examples.

Do you know why this issue may occur again and again?

![image](https://user-images.githubusercontent.com/17635022/32728232-8f5eb54c-c890-11e7-978c-aea791b69c4d.png)

P.S.  Also when I want to change mention's color, there appears a duplicated text on the back.
![image](https://user-images.githubusercontent.com/17635022/32728508-ac686376-c891-11e7-8fc3-b9a8123d7dfe.png)

**Comment by jfschwarz** [comment]
This happens if the font size / family in the textarea and the highlighter `div` behind it do not match. Please use DevTools element inspector to figure out which styles to adjust. Read more about how to customize styles of the component here: https://github.com/effektif/react-mentions#styling

**Comment by zenVentzi** [comment]
In case somebody gets here, using **css reset**, it could be causing the issue.
