### ISSUE TITLE
Minimum characters to trigger

### ISSUE THREAD

**Issue by renanpvaz** [effektif/react-mentions#206]
Is there a way to define, for example, that it needs at least 3 characters to show the mentions? Or perhaps limiting the number of suggestions. I'm dealing here with a big number of users in-memory.

**Comment by saidymadi** [comment]
yes that is easy.

in the case of async data in ur data provider function you would check if the search term contains  more than 3 letters before calling whatever source that u call to get ur results. 

otherwise return empty [ ]

**Comment by saidymadi** [comment]
https://github.com/saidymadi/react-mentions/blob/master/gh-pages/views/Application.js

look at my asyncData for more details
