### ISSUE TITLE
Changing markup breaks the displayed value

### ISSUE THREAD

**Issue by mvaivre** [effektif/react-mentions#211]
Hi there,

First of all, thanks for this project, it'll help me a lot (as soon as I resolve this issue ;)).
Here is the deal: whenever I set a custom markup, the displayed value in the mention switches from `display` to `id`.

Here is a simple snippet:
```javascript
<MentionsInput
  className="TextArea"
  onChange={onChange}
  value={value}
  markup="@[__type__](__id__)"
  >
  <Mention 
    trigger="#"
    className="Mention--cell"
    type="Cell"
    data={data.allCells && data.allCells.map((cell) => ({ id: cell.id, display: cell.name }) )}
  />
</MentionsInput>
```
In this example the mention will *always* display `cell.id`.

Even if I try to set a custom `displayTransform`  like `displayTransform={ (id, display) => display }`), it always ends up rendering ìd` instead!
If I remove my custom markup, everything is back to normal...

Thanks in advance for your help.

**Comment by mvaivre** [comment]
Ok, so I've just discovered that is renders correctly if you make sure you use `__display__` in your markup.

**Comment by jfschwarz** [comment]
The `data` provided for the `<Mention />` are only used for rendering suggestions (and generating the markup when a mention is selected). The `display` value is derived only from the markup value. There is no lookup from the `<Mention />`'s `data` prop happening.

**Comment by danlkv** [comment]
For anyone that has the same issue and really don't want to use `__display__` in their raw text: Use the displayTransform function, and lookup the display by id manually. 

I have no idea why this is not supported by default...

**Comment by Bilb** [comment]
> For anyone that has the same issue and really don't want to use `__display__` in their raw text: Use the displayTransform function, and lookup the display by id manually.
> 
> I have no idea why this is not supported by default...

Can you please explain what you mean exactly? I think I have the exact same usecase
