### ISSUE TITLE
jQuery.Deferred exception: Cannot read property 'jQuery321005094762707925462' of undefined TypeError: Cannot read property 'jQuery321005094762707925462' of undefined

### ISSUE THREAD

**Issue by niknokseyer** [effektif/react-mentions#212]
I have `react-mentions@1.2.1` installed.

Here's my code snippet:
```
                            <MentionsInput>
                                <Mention trigger="@"
                                         data={users} appendSpaceOnAdd="true"/>
                            </MentionsInput>
````

I just renders a textbox that I can't type in.

**Comment by frontendphil** [comment]
Hey @niknokseyer you need to provide `value` and `onChange` props to tell mentions what text to display and what should happen when the text changes.

**Comment by niknokseyer** [comment]
I'm still getting the error.

I tried something like this:
```
<MentionsInput value={{value}} onChange={this.onChange}>
                                <Mention trigger="@"
                                         data={this.props.users}
                                          />
                            </MentionsInput>
```

Where `onChange` is:
```
onChange(event, newValue, newPlainTextValue, mention) {
        value = newPlainTextValue
    }
```

It prints out something on the input box (textbox) but it's really slow. Like it takes a couple of seconds before it can display one.

**Comment by frontendphil** [comment]
Ok, I see one error straight away that is `{{value}}` which should be `{value}` because otherwise you're handing in an object. Also you should not assign `newPlainTextValue` to `value` but rather the real `newValue`. 

Anyhow coming back to the title of this issue. Since we're not using `jQuery` to build this component, we can also not cause any `jQuery` exceptions which is why I'm guessing that the actual error is somewhere in your application code.

**Comment by niknokseyer** [comment]
Sorry, yes.. the error is not related to mentions.

Unfortunately I still get the non-responsive (slow) textbox.

```

**Comment by jfschwarz** [comment]
It looks like you assign the new `newPlainTextValue` to a variable in the `onChange` handler. The React component will only update if you trigger a state update via `setState`. This might explain the unresponsiveness.
