### ISSUE TITLE
displayTransform function cannot return html tags

### ISSUE THREAD

**Issue by yadavsunil00001** [effektif/react-mentions#213]
displayTransform function which is given as prop to modify the mention is not able to return html <a> tag. It returns only String.Can it be fixed?

**Comment by frontendphil** [comment]
Hey @yadavsunil00001 since everything is mapped into a text `input` or `textarea` we cannot allow html to be returned form the `displayTransform` function. 

What exactly were you trying to do?

**Comment by yadavsunil00001** [comment]
I am trying to create a link to user page in the comment using userId and userName when the a user is tagged. Is it possible?

**Comment by frontendphil** [comment]
Yes, but this is not the scope of this component. We aim at providing highlighting within a text input. I guess rendering the link would ultimately happen after a comment has been submitted? In this case, you can simply post-process the comment using the markers `react-mentions` inserts. For instance if you have a comment with a user in there, that looks like: 

```
Hey @[John Doe](user:user-id-123), how's it going?
```

You can use a simple `RegExp` to transform that into the respective HTML you want. 

```html
Hey <a herf="/users/user-id-123>John Doe</a>
```

**Comment by yadavsunil00001** [comment]
Thanks for replying but i needed the link to be rendered while typing the comment ,even before the comment has been submitted.

**Comment by jfschwarz** [comment]
I'm afraid this will be difficult, because the `div` element with the highlighted mentions must lie behind the textarea so that all mouse events for setting the cursor/text selection reach the textarea. So supporting links is a bit out of scope for this component.

**Comment by dwilt** [comment]
@frontendphil We are trying to add a link (after it's been submitted). Thus, trying to follow your instruction:

> In this case, you can simply post-process the comment using the markers react-mentions inserts.

Do you have an example of what this would look like? Which `prop` would I use?

**Comment by frontendphil** [comment]
@dwilt the trick is to **not** render the `Mention` component when the comment has been submitted. You would then use the `value` you got from the component in the `onChange` handler and process it to replace the mentions of people with links. Does this make sense?

**Comment by dwilt** [comment]
@frontendphil thanks for the response. What we're actually trying to do is figure out a way to render text links inside of a submitted comment. Check out this gif before. We'd like to be able to turn "http://google.com/" into a link via `<a href="http://google.com/">http://google.com/</a>`

![2019-12-05 05 36 33](https://user-images.githubusercontent.com/1065539/70240076-730fdb00-1721-11ea-938a-3d54e2d7d6cb.gif)

Here is the input component markup:

```tsx
<MentionsContainer
  data-discussion-comment-textarea
  {...field}
  onChange={e => field.onChange({ target: { name: field.name, value: e.target.value } })}
  {...{ placeholder }}
  inputRef={textAreaRef}
  style={containerStyles}
  suggestionsPortalHost={host}
  allowSpaceInQuery
>
  <Mention
    type="user"
    trigger="@"
    data={hasFeature('enableMentions') ? users : []}
    style={{ position: 'relative', zIndex: 1, color: Colors.peacock5 }}
    renderSuggestion={data => <Suggestion {...data} />}
    appendSpaceOnAdd
  />
</MentionsContainer>
```
And the markup for the actual _rendering_ of the submitted comment:
```tsx
<MentionsContainer data-test="discussion-comment-body" value={body} disabled>
  <Mention
    type="user"
    trigger="@"
    data={[]}
    style={{ position: 'relative', zIndex: 1, color: Colors.peacock5 }}
  />
</MentionsContainer>
```

**Comment by dwilt** [comment]
@frontendphil while I've got you, may I ask, why is a `textarea` used to _render_ the output of a submitted comment? Aren't `textarea`s generally used within a `form` tag and a `p` would be used to render some content?

**Comment by dwilt** [comment]
After talking with a colleague of mine, who was the one that set this up, I think I know the approach you mean. We will not use `<MentionInput>` or `<Mention>` for the rendering but our own custom `<p>` and parse out the ids and links (and other items if we want) and replace them with our own custom tags.

**Comment by frontendphil** [comment]
> After talking with a colleague of mine, who was the one that set this up, I think I know the approach you mean. We will not use `<MentionInput>` or `<Mention>` for the rendering but our own custom `<p>` and parse out the ids and links (and other items if we want) and replace them with our own custom tags.

Exactly! :) By the way, we also have the use case of rendering links in user-created content. While it might be overkill for you we generally allow Markdown and then simply render this. Auto-linking is a standard feature so that would just work when someone pastes a link.

**Comment by RodolfoSilva** [comment]
I've made a little hook to convert the texts with mentions to metadata. 

@frontendphil , @jfschwarz Can I send a PR to add this hook as part of the library? 

Here is the code sandbox: https://codesandbox.io/s/usementionsmetadata-2f6wg

![image](https://user-images.githubusercontent.com/1703020/102296858-ff57ff00-3f2c-11eb-8352-11707f8fc8bc.png)


```tsx
import * as React from "react";

interface MentionMetadata {
  text: string;
  url?: string;
}

const SPLIT_PATTERN = /(@\[[^\]]+\]\([^)]+\))/;
const MENTION_PATTERN = /(?:@\[([^\]]+)\]\(([^)]+)\))/;

export default function useMentionsMetadata(
  text: string,
  getUrl: (params: string, name?: string) => string | undefined
): MentionMetadata[] {
  const metadata = React.useMemo(() => {
    const parts = text.split(SPLIT_PATTERN);

    const convertPartToMetadata = (part: string): MentionMetadata => {
      if (!part.startsWith("@")) {
        return { text: part };
      }

      const match = part.match(MENTION_PATTERN);

      if (!match || match.length < 3) {
        return { text: part };
      }

      const [, name, params] = match;

      const url = getUrl(params, name);

      if (url) {
        return {
          text: name,
          url: url
        };
      }

      return { text: name };
    };

    return parts.filter((part) => part !== "").map(convertPartToMetadata);
  }, [text, getUrl]);

  return metadata;
}
```

Usage:

```tsx
import * as React from "react";
import useMentionsMetadata from "./use-mentions-metadata";

export default function App() {
  const message = `Hey @[John Doe](user:user-id-123), how's it going?Hey @[John Doe](user:user-id-123), how's it going?
  @[John Doe](user:user-id-123) @[John Doe](user:user-id-123)
  contato@rodolfosilva.com
  @[]()
  @[x]()
  @[r](b)@[r](b)`;

  const metadata = useMentionsMetadata(message, (params) => {
    const userId = params.replace(/user:(.+)/g, "$1");
    return `#?userId=${userId}`;
  });

  return (
    <div className="App">
      <h1>Input</h1>
      <pre>{message}</pre>
      <h1>Output</h1>
      <pre>
        {metadata.map(({ text, url }, i) => {
          if (!url) {
            return <React.Fragment key={i}>{text}</React.Fragment>;
          }

          return (
            <a key={i} style={{ color: "green" }} href={url}>
              {text}
            </a>
          );
        })}
      </pre>
    </div>
  );
}
```

**Comment by udonmai** [comment]
@RodolfoSilva This is so great!!!!!!! Saved my day!

**Comment by goliney** [comment]
I wish there was an "official" tool to parse the resulting text, so it could be rendered. Isn't it the most common use case: render the text with mentions?
