### ISSUE TITLE
Problem Highlighter with format @username#id

### ISSUE THREAD

**Issue by AlexandreBourdeaudhui** [effektif/react-mentions#217]
Hello 👋 

I'm actually using `react-mentions` for my project, and i want use format `@username#id` (like Discord). But I encountered a problem when i select a name... If ID > 10, the format is broken

OK :
<img width="166" alt="capture d ecran 2018-01-17 a 14 54 01" src="https://user-images.githubusercontent.com/24500083/35046156-7f832eee-fb96-11e7-993c-9a6098897fc2.png">

NOK : 
![janv -17-2018 14-41-10](https://user-images.githubusercontent.com/24500083/35046038-1a7f3f92-fb96-11e7-8d26-60c37e90f6a0.gif)
<img width="838" alt="capture d ecran 2018-01-17 a 14 42 15" src="https://user-images.githubusercontent.com/24500083/35046045-1e4e7214-fb96-11e7-89be-6c48040c187e.png">

**Comment by jfschwarz** [comment]
See #21.

The regexp that is derived by react-mentions from the user provided markup format in [markupToRegex](https://github.com/effektif/react-mentions/blob/master/src/utils.js#L46) is non-greedy. It is designed to match markup that is encompassed by some pattern, e.g. `{__id__}`.

For your use case you would need greedy capturing groups. S.th. like `/@(\w+)#([0-9]+)/g`. Unfortunately, currently the regexp generation is not customizable.

**Comment by AlexandreBourdeaudhui** [comment]
Thanks for your fast answer 👍

**Comment by rubencodes** [comment]
@AlexandreBourdeaudhui unrelated question, how were you able to get the suggestions menu to pop up instead of popping down (default behavior)?
