### ISSUE TITLE
Set displayTransform depends on the mention type in case of multiple trigger

### ISSUE THREAD

**Issue by hazemkiwan** [effektif/react-mentions#218]
First, i wanna thank you for the project you did, it is very helpful for me. But i have a small issue should be solved.
I used a multiple trigger (@ and $). This is my code:
```
      <MentionsInput
        value={ this.state.value}
        style={defaultStyle}
        onChange={ this.handleIdeaBodyChange.bind(this) }
        markup="[__type__:__id__]"
        displayTransform={ (id) => `${id} ` }
      >
        <Mention
          type="admin"
          trigger="$"
          data={ this.getFirstDataMention }
          style={defaultMentionStyle}
        />
        <Mention
          type="user"
          trigger="@"
          data={ this.getSecondDataMention }
          style={defaultMentionStyle}
        />
      </MentionsInput>

```
What i need  is when the client try to mention an admin the result after pressing enter should be $ADMIN, and the result after mentioned a user the result should be @USER. The current result is ADMIN or USER .

Thanks

**Comment by jfschwarz** [comment]
This should be easy as the `displayTransform` function will be called with three arguments: `(id, display, type)`. So something like this should work:


```
displayTransform={ (id, display, type) => type === 'admin' ? '$ADMIN' :`@${id} ` }
```

**Comment by hazemkiwan** [comment]
Great!. Thank you.
