### ISSUE TITLE
Example usage?

### ISSUE THREAD

**Issue by richardkabiling** [effektif/react-mentions#25]
I've been trying to figure this component out. I had problems with retrieving the value of the input text, and had to check the code provided. I'm not sure if what I did was correct, but I ended up with:

``this.refs.mentionsinput.refs.input``

Then after that I had problems when triggering the suggestion overlay by pressing '@'. It seems my data was expected to have both 'display' and 'id'.

After that it still wouldn't work. It would be great if there was example usage.

**Comment by jfschwarz** [comment]
Checkout our examples page here: http://effektif.github.io/react-mentions/examples

Sources: https://github.com/effektif/react-mentions/tree/master/gh-pages/views/examples

Hope this helps.
