### ISSUE TITLE
React 0.13 warning

### ISSUE THREAD

**Issue by daviferreira** [effektif/react-mentions#29]
I'm getting the following warning using `react 0.13.3` and `react-mentions 0.1.4`.

`
Warning: Don't set .props.children of the React component <span />. Instead, specify the correct value when initially creating the element or use React.cloneElement to make a new element with updated props. The element was created by MentionsInput.
`

Probably because of https://github.com/effektif/react-mentions/blob/master/lib/MentionsInput.js#L184?

I will try to investigate further later on :)

**Comment by Kicu** [comment]
Started using react-mentions and I'm getting the same warning.
Was wandering if anything can be done with this issue? I really like my console clean ;)
