### ISSUE TITLE
Cursor position jumps back on white spaces in Mobile Chrome on Android

### ISSUE THREAD

**Issue by mihai** [effektif/react-mentions#30]
Typing in any `MentionsInput` field in the Chrome browser on Android jumps the cursor position backwards on white spaces, making it impossible to type free form text.

*Steps to reproduce*:
  1. Open latest Chrome (43.0.2357.93, updated 10 Jun) on an Android phone (tested on Nexus 5, Android 5.1)
  1. Go to http://effektif.github.io/react-mentions/
  1. Focus any of the example input fields and start typing a sentence

*Expected*: the cursor position stays at the end of whatever you've typed
*Actual*: the cursor jumps back (typically by the previous words' length) and breaks the typing flow

**Comment by mihai** [comment]
FWIW, it seems to be an issue with the predictive text feature of the Android keyboard that makes the cursor position jump. It works fine on mobile Firefox though.

**Comment by aymanosman** [comment]
Also found this issue

**Comment by nuc-gr** [comment]
Indeed the issue is caused by the auto-correction. 

When a word is marked for a suggestion, the `selectionStart` and `selectionEnd` are not reflecting the caret position but they wrap the whole word, even though the caret is somewhere in between and the actual selection is collapsed.

That leads into various issues, since the selection range is heavily used in the `handleChange` and `handleSelect` callbacks.

Simplest workaround for now is to pass the `autoComplete="off"` property in the `MentionsInput` component.

Otherwise I don't think there's a way to identify that the selection is not actually made by the user.

**Comment by mihai** [comment]
> Simplest workaround for now is to pass the autoComplete="off" property in the MentionsInput component.

@nuc-gr setting `autoComplete` doesn't fix the jumping cursor issue, tried both on the `form` and the `textarea` with no success.

**Comment by nuc-gr** [comment]
@mihai Are you sure the property is reaching the textarea element? 

You need either the [latest version](https://github.com/effektif/react-mentions/commit/809f123a795e6c74e2c4b20db092ee68275d019e) (which has some issues with the auto-growing of the textarea) or you can give it a try via a temp fix we have [in that fork](https://github.com/moviepilot/react-mentions/commit/e196b85041bdbba19fcfb421c97df6605d20d0ff).

I tried with Chrome in Android 4.2.2 and it works great.

**Comment by mihai** [comment]
> @mihai Are you sure the property is reaching the textarea element?

Yes I am, and upon inspecting the markup using Google's [remote debugging tools](https://developer.chrome.com/devtools/docs/remote-debugging) the attribute is indeed set on the `textarea`, however it doesn't seem to solve the issue.

I'm using latest Chrome (v43.0.2357.93) on Android 5.1.1.

**Comment by aymanosman** [comment]
Setting autoComplete to "off" fixes the issue for me.

**Comment by nuc-gr** [comment]
It works only in some Android versions :( 

Here is the relevant bug report for chromium: https://code.google.com/p/chromium/issues/detail?id=503132

**Comment by jfschwarz** [comment]
I just pushed a new branch autocorrect in an attempt to fix autocorrection. Any help on testing the branch on mobile Chrome would be much appreciated.

**Comment by frontendphil** [comment]
Just released 0.4.2 which includes this fix. Please note the breaking changes, of 0.4.0
