### ISSUE TITLE
autogrowTextarea messes up scroll position for long textareas

### ISSUE THREAD

**Issue by pocketjoso** [effektif/react-mentions#32]
Hi, thanks for awesome library! We currently use it on `state.com`, kudos!

The issue is [this line](https://github.com/effektif/react-mentions/blob/master/src/MentionsInput.jsx#L376) - setting the textarea height to `auto` (before then reapplying the actual height).

If textarea had a lot of content, pushing the height of the page, and the user was scrolled down towards the bottom of the page, then setting the height to `auto` will produce a `scroll position` outside of the page, and the browser will update it to be in range. The scroll position is then never updated again after the textarea is given back it's height. Result: Scroll position jumps up.

**Steps to reproduce**:
0. Have a page with a `react-mentions` textarea on it.
1. Write a looooot of text in it, enough so that it pushes the height of the page.
2. Scroll down to the bottom of the page.
3. Cause `react-mentions` to `render`

---

So I'm a bit curious - why are you resetting the height like this in the first place; what does it achieve? 

Cheers

**Comment by jfschwarz** [comment]
Thank you for reporting. We'll probably need a better solution for textarea auto-growing. The current implementation also does not react to window resize.

A good solution might be to make the textarea always fill its container div. The container div should grow with the highlighter's content. This way we could avoid setting an explicit height on the textarea at all.

Hope to find some time to implement this later today.

**Comment by jfschwarz** [comment]
> So I'm a bit curious - why are you resetting the height like this in the first place; what does it achieve?

It's for auto-shrinking of the textarea when the user deletes lines.

**Comment by pocketjoso** [comment]
> It's for auto-shrinking of the textarea when the user deletes lines.

Of course. Thanks so much for the quick fix!

**Comment by pocketjoso** [comment]
Btw have you looked at [the jumping android cursor issue](https://github.com/effektif/react-mentions/issues/30)? It's preventing us from fully using react mentions on mobile.. Cheers

**Comment by jfschwarz** [comment]
Re: "the jumping cursor issue": Have you tried if setting `autoComplete="off"` as suggested in https://github.com/effektif/react-mentions/issues/30#issuecomment-114162948 helps?

**Comment by mihai** [comment]
> Re: "the jumping cursor issue": Have you tried if setting autoComplete="off" as suggested in #30 (comment) helps?

@jfschwarz thanks for fixing this issue and for passing props to the `textarea` (i.e. 809f123a795e6c74e2c4b20db092ee68275d019e), however the `autoComplete="off"` solution doesn't work. Neither does `spellCheck="off"`, the only solution so far is turning off predictive text on the keyboard (i.e. replacing words on whitespace) but that involves users doing it themselves.

**Comment by jfschwarz** [comment]
@nuc-gr in https://github.com/effektif/react-mentions/issues/30#issuecomment-114263849 you mentioned

> some issues with the auto-growing of the textarea

Could it be that you have some CSS rules interfering with the inline styles that are now set to make the textarea auto-grow? It would be of great help, if you could find some time to report the issues you're seeing here. Thanks!
