### ISSUE TITLE
Add multiple trigger support?

### ISSUE THREAD

**Issue by kockok** [effektif/react-mentions#35]
Is it possible to listen to more than one trigger?
e.g. How to autocomplete both "@" and "#" from different sources?
Say, "@" listens to user ajax source.
Whilst "#" listens to tags source.

**Comment by jfschwarz** [comment]
Absolutely. Just add multiple `<Mention>` components as children of the `<MentionsInput>`.

```
<MentionsInput value={this.state.value} onChange={this.handleChange>
    <Mention trigger="@"
        data={this.requestUser}
        renderSuggestion={this.renderUserSuggestion} />
    <Mention trigger="#"
        data={this.requestTag}
        renderSuggestion={this.renderTagSuggestion} />
    <Mention />
</MentionsInput>
```
