### ISSUE TITLE
Async data provider

### ISSUE THREAD

**Issue by mir3z** [effektif/react-mentions#39]
Is it possible to use ajax request as a data provider? I can see that I can pass array or function in `data` prop but I don't know how async could be handled.

**Comment by jfschwarz** [comment]
Yes, you can pass a function as the `data` prop. The function can do both, return results synchronously, and pass the results to a callback (second function argument) asynchronously, like so for example:

```
var data = function(query, callback) {
    asyncQuery(query).then(callback);
};
```
