### ISSUE TITLE
Chinese/Japanese characters not supported

### ISSUE THREAD

**Issue by chrassendk** [effektif/react-mentions#40]
To reproduce: 
Switch language to Katakana (Japanese) and type "ka".

Output: "k" (Doesn't input the a and caret jumps back before "k")
Expected output: カ (Should combine "ka" to this)

Update:
- Seems to be connected to all accents as well
- Works "Single line input" / "Adv. options" - demo but not in the "Multiple trigger patterns" - demo

**Comment by rodrigues** [comment]
indeed, @chrassendk. `é`, for instance, does not work 😕

**Comment by Bertg** [comment]
This is probably related to an issue with the ```onChange``` event react emits. See [this issue](https://github.com/facebook/react/issues/3926) on react.

**Comment by jfschwarz** [comment]
This has been fixed by @Bertg with #47.
