### ISSUE TITLE
FF: Sentence is removed when using spellcheck

### ISSUE THREAD

**Issue by chrassendk** [effektif/react-mentions#41]
When users right-click on a misspelled word the words in the remaining sentence is deleted.

**Comment by pocketjoso** [comment]
Same in firefox (using `0.1.20`) - autocorrect deletes all text between *cursor and correction*. So no issue if you correct the last written word, but massive issue if you leave cursor at end of long text and then right click to auto correct something early in text! (issue does not occur in Chrome).

**Comment by martingg88** [comment]
sentence is removed as well if you try to edit any character at the middle of string. any solution to solve this issue?

**Comment by seratonik** [comment]
Experiencing this in Safari as well, added prop `spellCheck={false}` to `MentionsInput` to work around it for now.

**Comment by jfschwarz** [comment]
I just pushed a new branch `autocorrect` in an attempt to fix autocorrection. Any help on testing the branch on mobile Firefox would be much appreciated.

**Comment by frontendphil** [comment]
Just released 0.4.2 which includes this fix. Please note the breaking changes, of 0.4.0
