### ISSUE TITLE
Open suggestions above cursor

### ISSUE THREAD

**Issue by maxnowack** [effektif/react-mentions#48]
I would be great if the suggestions box will be opened above the cursor if there are not enough space below.

Example:
We have a comment stream with a "insert comment" form at the bottom of the body. if a user want to add a mention, the suggestions-box opens out of the body.

**Comment by frontendphil** [comment]
I would vote against this idea. If you can't display some options below your cursor position I would guess your controls are too close to the window border anyways. See the GitHub comment box for instance. Even if you resize your window the list still opens to the bottom. This way you also keep a consistent user experience. Changing the position to top, would also need to reverse the sorting and also the meaning of the up and down arrows.

**Comment by maxnowack** [comment]
Okay, you're maybe right.
What about limiting the displayed suggestions?

**Comment by frontendphil** [comment]
Can be easily done with CSS or the data source.

**Comment by justinobney** [comment]
I think this is a great idea. I am running into this while building a chat feature with the input box at the bottom of the screen. I want something similar to slack's input: 

![image](https://cloud.githubusercontent.com/assets/1054188/10064388/8dd7d034-623d-11e5-88a9-3ae68bb96da5.png)

**Comment by frontendphil** [comment]
Also the slack kind of displaying the suggestions is a pure CSS issue. 

    .suggestions {
        left: 0;
        bottom: 100%;

        width: 90%;
    }

and you get this kind of style. The reason why I'm so reluctant to including stuff like this is that our main focus of this component is retrieving mentions for a given set of keywords. We don't ship with CSS because the part of displaying should be totally up to you.

**Comment by maxnowack** [comment]
But you can navigate only with the `up` and `down` arrows, not `left` and `right`.

**Comment by amitava82** [comment]
This seems no longer works since `top` style attribute is overwritten.

**Comment by frontendphil** [comment]
We included an example that shows you how you can do it. It's in the "advanced" example.

**Comment by amitava82** [comment]
Thanks, it worked!

**Comment by abhisheksureshexperionglobal** [comment]
> Also the slack kind of displaying the suggestions is a pure CSS issue.
> 
> ```
> .suggestions {
>     left: 0;
>     bottom: 100%;
> 
>     width: 90%;
> }
> ```
> 
> and you get this kind of style. The reason why I'm so reluctant to including stuff like this is that our main focus of this component is retrieving mentions for a given set of keywords. We don't ship with CSS because the part of displaying should be totally up to you.

But this code is not working for me .. I want to display the list above the input element ..Any suggestion ?

**Comment by InvalidSB** [comment]
how can I control open/ close of suggestions in react mention? any ideas....please

**Comment by minhdandys2** [comment]
i use forceSuggestionsAboveCursor for MentionsInput
