### ISSUE TITLE
Any ideas on how test cases should be written?

### ISSUE THREAD

**Issue by tomchentw** [effektif/react-mentions#50]
Hi,

Thanks for the promising library.

Recently I'm trying to use it in my project. However, it seems hard for me to figure out how a test case should be written. I'd like to have the following test case:

```text
when a user types in `@tom`, it should show up a selection
```

and my test case is written as follows (in karma + mocha + sinon),

```js
var component = React.render(
    <MyMentionComponent // Uses MentionsInput internally
        renderAtSuggestion={callbackSpy} // Delegates to Mention.props.renderSuggestion
    />,
    div
);

expect(callbackSpy.called).to.be.false();
var textareaEl = React.findDOMNode(TestUtils.findRenderedDOMComponentWithTag(component, "textarea"));
textareaEl.focus();

textareaEl.value = "Initial text ...";
TestUtils.Simulate.change(textareaEl);
expect(textareaEl.value).to.equal("Initial text ...");

textareaEl.value = "Initial text ... @tom";
TestUtils.Simulate.change(textareaEl);
expect(textareaEl.value).to.equal("Initial text ... @tom");

expect(callbackSpy.called).to.be.true(); // fails here
```

I also tried to change the value of `textarea.value` using Chrome's console, and using jquery to trigger `change` event afterwards. It doesn't help either. Do you have any ideas on how to get it right?

Thanks

**Comment by jfschwarz** [comment]
The thing is, that the cursor position is used to determine whether or not to show the suggestions. You might want to try to simulate a selection change, roughly like this:

```
var cursorPosition = textareaEl.value.length; // set cursor to the end of the string
TestUtils.Simulate.select(textareaEl, { target: { selectionStart: cursorPosition, selectionEnd: cursorPosition } });
```

Hope this helps.

**Comment by tomchentw** [comment]
Oh yeah that works!!!! Thanks @jfschwarz
