### ISSUE TITLE
react 0.14 support

### ISSUE THREAD

**Issue by luisrudge** [effektif/react-mentions#52]
It's breaking right now:

![image](https://cloud.githubusercontent.com/assets/941075/10411808/6506a78a-6f48-11e5-9a59-b183424719fb.png)

**Comment by TomClarkson** [comment]
I see emptyFunction has been moved to fbjs https://github.com/facebook/react/issues/4564

**Comment by luisrudge** [comment]
Just create an empty func and use that. everywhere

**Comment by frontendphil** [comment]
Thanks for the issue. @jfschwarz is not around this week and I also got no time to fix this right now. If you find the time, I'm happy to accept a PR for this.

**Comment by luisrudge** [comment]
@frontendphil can you take a look in my pr? thanks!

**Comment by jfschwarz** [comment]
just released React 0.14 support with v0.2.0

**Comment by TomClarkson** [comment]
![screen shot 2015-10-22 at 8 40 44 am](https://cloud.githubusercontent.com/assets/2054503/10648020/88744688-7898-11e5-8cf4-826237476f8b.png)
