### ISSUE TITLE
ReactJS 0.14 issues

### ISSUE THREAD

**Issue by oizie** [effektif/react-mentions#55]
Hi. Before I was using the dist/react-mentions.js in our project and was working fine. now with the update toReactJS v0.14.0 and this new update in react-mentions (v0.2.0) I keep receiving this error: 

Uncaught TypeError: Cannot read property 'firstChild' of undefinedReactMount.findComponentRoot @ react-mentions.js:11877ReactMount.findReactNodeByID @ react-mentions.js:11841getNodeFromInstance @ react-mentions.js:11347findDOMNode @ react-mentions.js:16361module.exports.React.createClass.updateSuggestionsPosition @ react-mentions.js:504module.exports.React.createClass.componentDidUpdate @ react-mentions.js:534assign.notifyAll @ react-with-addons.js:889ON_DOM_READY_QUEUEING.close @ react-with-addons.js:13487Mixin.closeAll @ react-with-addons.js:17301Mixin.perform @ react-with-addons.js:17248Mixin.perform @ react-with-addons.js:17235assign.perform @ react-with-addons.js:15303flushBatchedUpdates @ react-with-addons.js:15364ReactPerf.measure.wrapper @ react-with-addons.js:12861Mixin.closeAll @ react-with-addons.js:17301Mixin.perform @ react-with-addons.js:17248ReactDefaultBatchingStrategy.batchedUpdates @ react-with-addons.js:8833batchedUpdates @ react-with-addons.js:15311ReactEventListener.dispatchEvent @ react-with-addons.js:10334

**Comment by TomClarkson** [comment]
Are you able to fix this? I'm waiting on react-mentions to upgrade

**Comment by frontendphil** [comment]
@jfschwarz is on leave for the next 3 weeks... We're also a bit short on spare time because we're releasing a new major version of our main product (effektif ;)) next month. But I think I can look into the issue today.

**Comment by frontendphil** [comment]
I just published 0.2.1, could you check if this works now?

**Comment by TomClarkson** [comment]
This works great, thanks very much :)
