### ISSUE TITLE
AMD style

### ISSUE THREAD

**Issue by martingg88** [effektif/react-mentions#59]
any guide on how to use this with amd style?

i do have react.createClass is undefined with integrate with amd style. any idea?

**Comment by frontendphil** [comment]
Ist `React` undefined or `createClass`? Which version are you trying to use? Importing directly from `lib` or the concatenated version in `dist`? The one in `dist` should work, however you will need to have `React` available on the global (`window`) scope.

**Comment by martingg88** [comment]
it is React undefined..i have imported 0.2.2 from lib. 

if i try to build your fileds in src folder with webpack and i do have following error.
any idea?
addComponentAsRefTo(...): Only a ReactOwner can have refs.

**Comment by frontendphil** [comment]
You got a line number, file for me?

**Comment by martingg88** [comment]
Uncaught Error: Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded (details: https://fb.me/react-refs-must-have-owner).

react-with-addons.js:20242

**Comment by frontendphil** [comment]
This sounds more like an issue with your build than with react-mentions.

**Comment by martingg88** [comment]
i just using following command to build your src files.

webpack --output-library="ReactMentions" --output-library="umd" index.js react-mentions.js

**Comment by frontendphil** [comment]
Since you are using webpack, you should be able to require anything from within the libs without problems. Definitively you should not need to re-build react-mentions as your last post suggests.

**Comment by martingg88** [comment]
thanks for your info.
