### ISSUE TITLE
limit the number of suggestions rendered

### ISSUE THREAD

**Issue by luisrudge** [effektif/react-mentions#64]
I'm rendering a big list of suggestions. It would be great to render just a few so that my page doesn't scroll until the end of times :stuck_out_tongue_closed_eyes:

**Comment by frontendphil** [comment]
Well you can simply reduce the items you hand in to the `data` property. You can also use a function callback there so that you can return a subset of your data based on whatever other property you want.

**Comment by luisrudge** [comment]
I can't use the data property, because I need to do that after the user starts typing.. If I do that before, I'll just get the first ones and the rest won't be available in the data source.

**Comment by frontendphil** [comment]
I don't understand. If you use a function for as a dataProvider then it will be invoked with each keystroke of the user. So you can always limit the size of the returned data.

**Comment by luisrudge** [comment]
ahhhh, sorry! I didn't know you could pass a function (just saw it in the docs, sorry). Thanks!
