### ISSUE TITLE
Enable searching in suggestions even after pressing space

### ISSUE THREAD

**Issue by hingermayank** [effektif/react-mentions#67]
One might have many results for first name, so a user should be allowed to search even in last name after pressing space. But in current scenario, the suggestion box closes as soon as he/she presses space.

**Comment by JonathanKolnik** [comment]
Hi, do you guys have anything in the works for this, I'd love to help in any way if you need contributors.

**Comment by johannesnagl** [comment]
I solved this with using the following regexp as a trigger value:

```
new RegExp('(?:^|\\s)(@([^@]*))$')
````

the trigger value itself is a `@`.

**Comment by JonathanKolnik** [comment]
Awesome thank you @johannesnagl!

**Comment by johannesnagl** [comment]
@JonathanKolnik feel free to comment on this one if you encounter any problems. My team mates who tested my addition from the weekend we're really happy -  so I guess it's working fine :)

**Comment by chrisgervang** [comment]
Before seeing this issue I encountered the same problem and came to the same conclusion @johannesnagl did. I feel it is appropriate to consider making this the default behavior and opened #133.

**Comment by frontendphil** [comment]
Closing because this has been fixed.
