### ISSUE TITLE
不能连续输入中文 (Input via IME broken)

### ISSUE THREAD

**Issue by vjzning** [effektif/react-mentions#68]
![image](https://cloud.githubusercontent.com/assets/5629031/12138595/0e4f63ea-b495-11e5-8698-7bfd4c9f2776.png)

After press the space bar

![image](https://cloud.githubusercontent.com/assets/5629031/12138607/2133afca-b495-11e5-9d56-faa4f8715262.png)

**Comment by jfschwarz** [comment]
@vjzning If you have any time to spare, could you maybe test if the branch `autocorrect` behaves better for Chinese input? This would be of great help!

**Comment by southerncross** [comment]
Great! :+1:  I tested and it worked!


Before (IME broken):
![untitled2](https://cloud.githubusercontent.com/assets/3861465/14007339/ba0b0f24-f1b0-11e5-9ab9-954d7c11ca3c.gif)

After(fixed):
![untitled](https://cloud.githubusercontent.com/assets/3861465/14007334/b2426558-f1b0-11e5-86f6-627edaf95e58.gif)

**Comment by southerncross** [comment]
Here is a related post, you can check it.

[composition-event](http://blog.evanyou.me/2014/01/03/composition-event/)

**Comment by vjzning** [comment]
@southerncross  怎么修复的？

**Comment by southerncross** [comment]
@vjzning The auto-correction feature fixed Chinese-input problem. I didn't read the source code carefully  :sweat_smile:

**Comment by frontendphil** [comment]
Just published 0.4.2 which includes a fix for this. Please mind the breaking changes of 0.4.0.

**Comment by eyesofkids** [comment]
look like react onchange issue here: [https://github.com/facebook/react/issues/3926](https://github.com/facebook/react/issues/3926)
