### ISSUE TITLE
Missing onFocus/onBlur properties

### ISSUE THREAD

**Issue by t1mmen** [effektif/react-mentions#69]
`MentionsInput`doesn't support `onFocus` and `onBlur`, but it looks to be fairly easy to implement based on the source code. Is this planned already, or should I take a stab at a PR?

**Comment by jfschwarz** [comment]
`MentionsInput` *does* support `onFocus` and `onBlur`. (It's not documented but we don't feel this would be necessary.)

**Comment by t1mmen** [comment]
Oh wow, that's embarrassing. I had an invisible character in the value I set `onFocus`/`onBlur`, sorry about that!
