### ISSUE TITLE
Document callback in data filtering function

### ISSUE THREAD

**Issue by fremn** [effektif/react-mentions#70]
EDIT: originally i was going to ask if this was possible / if you would be open to the functionality being added but Looking at the source it looks like it may already be possible.
/////
First off Great work here. 

Rather than passing in an array of data id like to be able to pass in a function 

looking at the source it seems this might be possible by doing
```
<Mention data= {(query, callback) => request.get(query).then(callback))} />
```   
am i off or is this an undocumented feature?

**Comment by jfschwarz** [comment]
Yep, you can totally do that. Indeed, the possibility to use the callback passed to the filtering function is not properly documented yet.

**Comment by jfschwarz** [comment]
README has been updated
