### ISSUE TITLE
access suggestion data besides id and display

### ISSUE THREAD

**Issue by fremn** [effektif/react-mentions#73]
So when rendering suggestions id like to have access info besides just the display and id. (specifically i have an image url and email)

it looks like the solution would be to modify `renderContent` to just pass in the `suggestion` object

```javascript
renderContent: function(id, suggestion, { mentionDescriptor, query }) {
    var display = this.getDisplay(suggestion);
    var highlightedDisplay = this.renderHighlightedDisplay(display, query);

    if(mentionDescriptor.props.renderSuggestion) {
      return mentionDescriptor.props.renderSuggestion(id, display, query, highlightedDisplay, suggestion);
    }

    return highlightedDisplay;
  },
``` 

however I could see how that starts to get busy.

**Comment by fremn** [comment]
workaround here is to store the results in an object on the component wrapping MentionsInput when they come in using the function passed to data prop. and then in the function passed to renderSuggestion fetch the original suggestion object

**Comment by jfschwarz** [comment]
Not sure if I completely get your proposal... Do you want to pass the full suggestion object to the user provided `renderSuggestion` function? Actually, the idea was that the query result data provided to the Mention components adheres to the fixed schema `{ id, display }`, so I guess your "workaround" pretty much is how it was intended to be used.

Of course it would be no big deal to simply pass through the full suggestion object with all custom properties. If it is passed to `renderSuggestion` as the last argument it also won't break the API. Your example code looks promising, so if you care to submit a PR I'm happy to accept it.

**Comment by johannesnagl** [comment]
> Do you want to pass the full suggestion object to the user provided renderSuggestion function?

yes, same here! I would love to pass an object with more than id, display. maybe avatar or more infos (think of: verified flag for twitter/facebook profiles).

**Comment by jfschwarz** [comment]
The signature of `renderSuggestion` has been updated to `(entry, search, highlightedDisplay) => Element` in v0.3.0 (`entry` being the full data entry object).

**Comment by mishozhghenti** [comment]
Is it possible to give customized markup like @[UserName](UserId)(UserMail) ? The data fetched from API contains UserMail but it is not visible in that formating.
