### ISSUE TITLE
access to other event data from onChange

### ISSUE THREAD

**Issue by fremn** [effektif/react-mentions#74]
i see why the mockEvent is needed for modifying the value. 

is there a reason it doesn't include event info such as keyCode etc? 

`https://github.com/effektif/react-mentions/blob/master/src/MentionsInput.jsx#L382` 
```

    // Propagate change
    // var handleChange = this.getOnChange(this.props) || emptyFunction;
    var eventMock = { target: { value: newValue } };  
    // this.props.onChange.call(this, eventMock, newValue, newPlainTextValue, mentions);
    this.executeOnChange(eventMock, newValue, newPlainTextValue, mentions);
```
Im thinking something like
```
var eventMock = fbjs.clone(ev) // or something idk
eventMock.target.value = newValue
``

**Comment by jfschwarz** [comment]
No special reason, but so far just including the value has been sufficient. I wouldn't like to do a full clone as that seems quite expensive and not really necessary, but we might add additional info on a property by property basis if someone comes up with a use case where it's really needed. However, `change` events do not even have a  `keyCode` property, and looking at the other event properties they don't seem that useful after all...

**Comment by fremn** [comment]
wow fail on my part.
