### ISSUE TITLE
\r\n counts as 2 for length purposes instead of 1

### ISSUE THREAD

**Issue by fbatista** [effektif/react-mentions#75]
Hi, so, using the ReactMentions component on a scenario where data comes from the server, after being sent for storage in a previous request (imagine a comment / post edit screen or something similar), the textarea will behave super strangely, when performing editions.

I was able to narrow this to the fact that the data from the server had newlines represented as \r\n instead of just \n. This caused the component to make a mistake when performing the calculation for the caret position and deleting / adding text in the wrong position.

My workaround was to change my getInitialState to do this:

```
  getInitialState() {
    let badNewLine = /\r\n/gm;
    let goodNewLine = "\n";
    return {
      value: this.props.defaultValue.replace(badNewLine, goodNewLine)
    };
  },
```

It feels hacky and something that the component itself should take care of for me. 

TL,DR:
"\r\n".length == 2
"\n".length == 1
This cause data loaded in with the \r\n format to cause wacky behaviour.

**Comment by frontendphil** [comment]
Well those are two characters after all ;) Not sure about this one, but my gut feeling is, that we should not do this clean-up step. After all, you need to hand in the correct data when using the component. However, we might issue a warning whenever we see something like this. 

The reason for me would be, that data should be clean before you start working with it, not afterwards. If we start removing stuff, then this would be kinda weird. By doing it yourself, you can remove the `\r` before and add them afterwards if they are needed. 

@jfschwarz do you have any thoughts on this?

**Comment by johannesnagl** [comment]
we experienced the same problem today. Our solution/workaround was to replace the `\r\n` in the onChange with the following code: `textareaValue.replace(/\r\n/g, '\n')`

**Comment by marinona** [comment]
I'm having the same problem as well.
I need to load a default value from the server and if it has `\n\r`  it causes problems.
I'll do something similar to @johannesnagl 's workaround, but I also think this should be handled by the component itself!
