### ISSUE TITLE
Styling

### ISSUE THREAD

**Issue by johannesnagl** [effektif/react-mentions#76]
I'm not sure, but docs are missing any infos about how we should properly style the react-mentions plugin.

I found a "react-mentions.less" file within the gh-pages/less/ folder, but when including this, i do not only receive styling for "react-mentions …" selectors, but also basic stuff like body, h1-h5, .header stylings.

so what's the preferred way to implement any css? should we do this on our own?

**Comment by jfschwarz** [comment]
We chose a "style-free" approach, meaning that the lib does not ship with any CSS or LESS. We're only setting the most essential inline style definitions for the UI to be usable. Thus, you're free to use your favorite styling method, whatever it is (css/less/scss/inline/...). 

The react-mentions.less file in the gh-pages dir is only for our examples page and not intended as a theme. So yes, you have to do the styling on you own. (In our experience, it is often easier to start from a minimally styled widget, than overwriting CSS to customize the default theme.)
