### ISSUE TITLE
Expose utils.js helper methods

### ISSUE THREAD

**Issue by JonathanKolnik** [effektif/react-mentions#77]
I would like to be able to use iterateMentionsMarkup from utils.js so that I can convert the plainText back to the marked up text, but convert them to links. 

Change is: 

src/index.js
```
'use strict';

module.exports = {
  MentionsInput: require('./MentionsInput'),
  Mention: require('./Mention'),
  Utils: require('./Utils') #exposing helper methods
};
```

**Comment by jfschwarz** [comment]
I wouldn't really like to make the Utils part of the public API, which should have a minimal surface area. You can, however, access the utils functions by importing the module directly from `'react-mentions/lib/utils'`.
