### ISSUE TITLE
Markup doesn't work without __display__ when using multiple triggers

### ISSUE THREAD

**Issue by JonathanKolnik** [effektif/react-mentions#79]
Original markup was: 

`@[__display__](__type__:__id__)`

This worked great with both 1 trigger, @, and also when I added a second, *. 
However, I want to drop the \__display\__ from the markup and this throws the error

 `Since multiple Mention components have been passed as children, the markup has to define the __type__ placeholder` 

I'm not sure why it isn't catching the \__type\__ anymore.

**Comment by jfschwarz** [comment]
Thanks for finding a stupid bug! :) Fixed in v0.2.8

**Comment by JonathanKolnik** [comment]
Np, thank you for the quick reply and fix!

**Comment by JonathanKolnik** [comment]
@jfschwarz I see that the npm package is on 2.8, but the change isn't there when I install the new version locally. I see that the dist is still on the 2.7, not sure if that's related. Thanks again.

**Comment by jfschwarz** [comment]
ahh, sorry I messed up the release. please use v0.2.9
