### ISSUE TITLE
No support for multi word searches

### ISSUE THREAD

**Issue by johannesnagl** [effektif/react-mentions#81]
If I want to search for "Vienna Paladins" the autocomplete stops at "vienna" - so it looks like that it's currently not possible to search for terms with multiple words. 

This is especially important for remote searches, where we can't display suggestions upfront.

**Comment by johannesnagl** [comment]
maybe a duplicate of #67

**Comment by jfschwarz** [comment]
Closing this, as indeed it is a duplicate of #67
