### ISSUE TITLE
Allow HTML for renderSuggestion

### ISSUE THREAD

**Issue by johannesnagl** [effektif/react-mentions#82]
After fixing #73 it's now possible to render a suggestion based on arbitrary properties. I really would like to have a chance to render html or at least an image tag. (think of user-avatar, …)

I would totally be fine with having a default "only text" and a way to enable HTML, maybe with "renderSuggestionAsHTML" attribute?

**Comment by frontendphil** [comment]
Not sure what you mean. In the `renderSuggestion` callback you can return whatever you want. So if you like to render an image, go ahead and return `<img src="whatever" />`. Or am I missing something?

**Comment by frontendphil** [comment]
Ah or do you mean inside the highlighted text?

**Comment by johannesnagl** [comment]
> Or am I missing something?

yes, html is getting escaped! :) I tried the following: 

```
return entry.display + ' <img src="whatever.png">';
``` 

and it was escaped to `Foobar <img src="whatever.png" />`

**Comment by frontendphil** [comment]
Have you tried returning _real_ react components?

```
return (
  <span>
    { entry.display }
    <img src='...' />
  </span>
);
```

**Comment by johannesnagl** [comment]
awesome! returning a jsx-based component works! haven't thought about this one.
