### ISSUE TITLE
Not compatible with SwiftKey Keyboard on Android

### ISSUE THREAD

**Issue by bbmreed** [effektif/react-mentions#93]
Steps to reproduce:
- install swiftkey https://swiftkey.com/en/keyboard/android
- using the demo site: http://effektif.github.io/react-mentions/
- In any of the inputs
- type `@`, choose `John Doe`
- mention gets inserted (so far so good)
- press space to keep typing
- mention disappears 

My basic understanding of what might be happening:
- type `@`, choose something
- react-mentions inserts the mention into the text input, so far so good
- press space (to keep typing)
- swiftkey tracks its own state of the text, which has changed out from under it
- swift asserts its state of the text into the input
- all the text react-mentions inserted is now completely replaced, with whatever swift wants the text to be

In the example I gave, the mention is completely removed. In our app we're using usernames (eg `@mike`), and swift will replace the mention `@mike` with the literal text `@mike`, breaking the mention. Swift's replacements aren't stable enough for us to parse the text server side for mentions, as it might autocorrect `@mike10` with `@mike`.

My sense is that this going to be tough to support, but I thought I'd report it anyways.

**Comment by elimisteve** [comment]
Is this still an issue?

**Comment by frontendphil** [comment]
I'm closing this since it doesn't seem to have been a big issue since 2016.
